# Generated by Django 3.0.2 on 2020-01-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippers',
            old_name='delivery_licence',
            new_name='deriving_licence',
        ),
        migrations.AlterField(
            model_name='foods',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
