# Generated by Django 3.0.2 on 2020-01-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200124_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurents',
            name='email',
            field=models.EmailField(default='taz@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='restaurents',
            name='password',
            field=models.CharField(default='password', max_length=12),
        ),
        migrations.AddField(
            model_name='shippers',
            name='email',
            field=models.EmailField(default='null', max_length=254),
        ),
        migrations.AddField(
            model_name='shippers',
            name='password',
            field=models.CharField(default='password', max_length=12),
        ),
        migrations.AlterField(
            model_name='restaurents',
            name='address',
            field=models.TextField(default='Bangalore'),
        ),
    ]
