# Generated by Django 3.0.2 on 2020-01-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200125_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippers',
            name='password',
            field=models.CharField(default='password', max_length=10),
        ),
    ]
