# Generated by Django 3.0.2 on 2020-01-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200125_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurents',
            name='mob_no',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='shippers',
            name='mob_no',
            field=models.CharField(max_length=12),
        ),
    ]
