# Generated by Django 3.0.2 on 2020-01-28 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_designations'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='restaurent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.Restaurents'),
        ),
    ]
