# Generated by Django 3.0.2 on 2020-01-31 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_category_restaurent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='restaurent',
        ),
        migrations.AddField(
            model_name='foods',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
