# Generated by Django 3.0.2 on 2020-02-12 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='user',
        ),
        migrations.AddField(
            model_name='foods',
            name='restaurent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.Restaurents'),
        ),
    ]
