# Generated by Django 3.0.2 on 2020-02-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200212_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='image',
            field=models.ImageField(default='', upload_to='food_images/'),
        ),
    ]
