# Generated by Django 3.0.2 on 2020-02-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200213_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
