# Generated by Django 3.0.2 on 2020-02-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200216_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurents',
            name='locality',
            field=models.CharField(default='', max_length=50),
        ),
    ]
