# Generated by Django 3.0.2 on 2020-02-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_restaurents_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurents',
            name='locality',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
