# Generated by Django 3.0.2 on 2020-02-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200224_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='price',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='quentity',
            field=models.CharField(max_length=5000),
        ),
    ]
