# Generated by Django 3.0.2 on 2020-02-27 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200224_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='food_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Foods'),
        ),
    ]
