# Generated by Django 3.0.2 on 2020-02-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200227_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='total_price',
        ),
        migrations.AddField(
            model_name='orders',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='quentity',
            field=models.IntegerField(),
        ),
    ]
