# Generated by Django 3.0.2 on 2020-03-01 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0024_auto_20200228_0622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='like',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='foods_id',
        ),
        migrations.AddField(
            model_name='ratings',
            name='restaurents_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.Restaurents'),
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('coustomer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('restaurents_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Restaurents')),
            ],
        ),
    ]
