# Generated by Django 3.0.2 on 2020-03-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20200301_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurents',
            name='avarage_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurents',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
