# Generated by Django 3.0.2 on 2020-03-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20200301_1827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reviews',
        ),
    ]
