# Generated by Django 3.0.2 on 2020-03-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_communicat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_designations',
            name='designations',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
