# Generated by Django 3.0.2 on 2020-03-08 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20200304_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicat',
            name='date',
            field=models.DateField(default=datetime.date(2020, 3, 8)),
        ),
        migrations.AddField(
            model_name='reviews',
            name='date',
            field=models.DateField(default=datetime.date(2020, 3, 8)),
        ),
    ]
