# Generated by Django 3.0.2 on 2020-03-14 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20200309_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicat',
            name='date',
            field=models.DateField(default=datetime.date(2020, 3, 14)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateField(default=datetime.date(2020, 3, 14)),
        ),
    ]
