# Generated by Django 3.0.2 on 2020-03-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20200314_1835'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orders',
            managers=[
            ],
        ),
    ]
