# Generated by Django 3.0.2 on 2020-03-15 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20200315_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 18, 12, 30, 176402)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateField(default=datetime.date(2020, 3, 15)),
        ),
    ]
