# Generated by Django 3.0.2 on 2020-03-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20200323_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='accepet_by_rest',
            field=models.BooleanField(default=False),
        ),
    ]
