# Generated by Django 3.0.2 on 2020-03-24 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_orders_accepet_by_rest'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_statuses',
            field=models.CharField(choices=[('O', 'ORDERD'), ('A&P', 'ACCEPT & PREPARING'), ('R', 'REJECT'), ('RD', 'READY FOR DELIVERY'), ('P&D', 'PICKED UP & ON ROAD'), ('D', 'DELIVERED')], default='O', max_length=20),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateField(default=datetime.date(2020, 3, 24)),
        ),
    ]
