# Generated by Django 3.0.2 on 2020-03-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_auto_20200331_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippers',
            name='Vachile_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='shippers',
            name='Vechile_no',
            field=models.CharField(default='', max_length=17),
        ),
    ]
