# Generated by Django 3.0.2 on 2020-04-01 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20200331_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippers',
            name='locality',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
    ]
