# Generated by Django 3.0.2 on 2020-04-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_auto_20200401_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='received_by_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
