# Generated by Django 3.0.2 on 2020-04-01 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0050_orders_received_by_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippers',
            name='shipper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
