# Generated by Django 3.0.2 on 2020-04-01 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_auto_20200401_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='shipper_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Shippers'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='restaurents_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Restaurents'),
        ),
    ]
