# Generated by Django 3.0.2 on 2020-04-03 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20200401_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippers',
            name='total_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateField(default=datetime.date(2020, 4, 3)),
        ),
    ]
