# Generated by Django 3.0.2 on 2020-04-06 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20200403_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippers',
            name='is_in_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_statuses',
            field=models.CharField(choices=[('O', 'ORDERD'), ('A&P', 'ACCEPT & PREPARING'), ('R', 'REJECT'), ('RD', 'READY FOR DELIVERY'), ('P&D', 'PICKED UP & ON ROAD'), ('S', 'SUCCESS')], default='O', max_length=20),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateField(default=datetime.date(2020, 4, 6)),
        ),
    ]
